<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\URL;
use Illuminate\Http\Request;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     * 
     * This method is used to bind services into the service container.
     * It's typically used to register bindings or dependencies in your app.
     */
    public function register(): void
    {
        // You can register services here if needed
        // Example: $this->app->bind(SomeInterface::class, SomeImplementation::class);
    }

    /**
     * Bootstrap any application services.
     * 
     * This method is used for setting up or bootstrapping any necessary application services.
     * In this case, it's used to force HTTPS on production environments.
     */
    public function boot(): void
    {
        // Check if the application is running in the 'production' environment
        if (env('APP_ENV') === 'production') {
            // Force HTTPS scheme for all URLs generated by Laravel
            URL::forceScheme('https');
        }
    }
}